sudo: false
dist: xenial
language: node_js

services:
  - xvfb

matrix:
  include:
    - node_js: "12"
      addons:
        firefox: "60.0"
      env: BROWSER=true MAKE_TEST=true
    - node_js: "10"
      env: BROWSER=false MAKE_TEST=false
    - node_js: "12"
      env: BROWSER=false MAKE_TEST=false
     
    # Power jobs
    - node_js: "12"
      addons:
        firefox: "60.0"
      env: BROWSER=true MAKE_TEST=true
      arch: ppc64le
    - node_js: "10"
      env: BROWSER=false MAKE_TEST=false
      arch: ppc64le
    - node_js: "12"
      env: BROWSER=false MAKE_TEST=false
      arch: ppc64le
env:
  matrix: BROWSER=false MAKE_TEST=false

after_success: npm run coveralls


# Needed to run Karma with Firefox on Travis
# http://karma-runner.github.io/0.13/plus/travis.html
before_script:
  - sudo apt-get install -y make
  - make --version

script:
  - "[ $BROWSER == true ] || npm test"
  # ensure buildable
  - "[ $MAKE_TEST == false ] || make -j 4"
  # test in firefox
  - "[ $BROWSER == false ] || npm run mocha-browser-test"
